version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ./config:/config
      - /homelab/media/tv-show:/tv #optional
      - /homelab/docker/qBittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
